use crate::AnalysisResult;
use std::fs::File;
use std::io::Write;
use std::path::Path;

pub fn generate_html_report(results: &[AnalysisResult], output_path: &Path) -> anyhow::Result<()> {
    let mut file = File::create(output_path)?;

    writeln!(file, "<!DOCTYPE html>")?;
    writeln!(file, "<html lang='en'><head>")?;
    writeln!(file, "<meta charset='UTF-8'>")?;
    writeln!(file, "<meta name='viewport' content='width=device-width, initial-scale=1.0'>")?;
    writeln!(file, "<title>LENSINT Forensic Report</title>")?;
    writeln!(file, "<style>")?;
    writeln!(file, "body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f5f7; color: #333; margin: 0; padding: 20px; }}")?;
    writeln!(file, "h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}")?;
    writeln!(file, ".card {{ background: #fff; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}")?;
    writeln!(file, ".hash {{ font-family: monospace; color: #e74c3c; }}")?;
    writeln!(file, ".alert {{ color: #c0392b; font-weight: bold; }}")?;
    writeln!(file, "table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}")?;
    writeln!(file, "th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}")?;
    writeln!(file, "th {{ background-color: #ecf0f1; }}")?;
    writeln!(file, "</style>")?;
    writeln!(file, "</head><body>")?;

    writeln!(file, "<h1>LENSINT Forensic Examination Report</h1>")?;
    writeln!(file, "<p>Generated by Lensint Rust Engine v1.0.0</p>")?;

    for res in results {
        writeln!(file, "<div class='card'>")?;
        writeln!(file, "<h2>Target: {}</h2>", res.file_path)?;
        
        if let Some(err) = &res.error {
            writeln!(file, "<p class='alert'>Analysis Error: {}</p>", err)?;
        } else {
            writeln!(file, "<table>")?;
            writeln!(file, "<tr><th>Metric</th><th>Value</th></tr>")?;
            
            if let Some(hashes) = &res.hashes {
                writeln!(file, "<tr><td>SHA256</td><td class='hash'>{}</td></tr>", hashes.sha256)?;
                writeln!(file, "<tr><td>MD5</td><td class='hash'>{}</td></tr>", hashes.md5)?;
                writeln!(file, "<tr><td>File Size</td><td>{} bytes</td></tr>", hashes.file_size)?;
            }

            if let Some(ela) = res.ela_score {
                writeln!(file, "<tr><td>ELA Score</td><td>{:.2}</td></tr>", ela)?;
            }
            
            if let Some(ghost) = res.jpeg_ghost_variance {
                writeln!(file, "<tr><td>JPEG Ghost Variance</td><td>{:.4}</td></tr>", ghost)?;
            }

            if let Some(cmfd) = res.cmfd_clones {
                let color = if cmfd > 0 { "class='alert'" } else { "" };
                writeln!(file, "<tr><td>Copy-Move Clones Found</td><td {}> {}</td></tr>", color, cmfd)?;
            }

            if let Some(lsb) = res.lsb_entropy {
                let color = if lsb > 7.95 { "class='alert'" } else { "" };
                writeln!(file, "<tr><td>LSB Entropy</td><td {}> {:.4}</td></tr>", color, lsb)?;
            }

            writeln!(file, "<tr><td>ASCII Strings Found</td><td>{}</td></tr>", res.strings_found)?;
            writeln!(file, "<tr><td>Embedded Images Carved</td><td>{}</td></tr>", res.carved_images)?;

            if !res.threat_signatures.is_empty() {
                let threats = res.threat_signatures.join(", ");
                writeln!(file, "<tr><td>Threat Signatures</td><td class='alert'>{}</td></tr>", threats)?;
            } else {
                writeln!(file, "<tr><td>Threat Signatures</td><td>Clean</td></tr>")?;
            }

            writeln!(file, "</table>")?;
        }
        
        writeln!(file, "</div>")?;
    }

    writeln!(file, "</body></html>")?;
    Ok(())
}
