"""Automated YARA Rule Generator from LENSINT Forensics Findings.

Generates deployable YARA detection rules from suspicious image attributes,
hashes, carved payloads, extracted strings, and webshell signatures.
"""
from __future__ import annotations

import re
import time
from typing import Optional
from lensint.core.models import AnalysisResult


def generate_yara_rule(result: AnalysisResult, rule_name: Optional[str] = None) -> str:
    """Generate a clean, deployable YARA rule from forensic analysis result."""
    clean_name = rule_name or f"LENSINT_Threat_{result.integrity.sha256[:12]}"
    clean_name = re.sub(r"[^a-zA-Z0-9_]", "_", clean_name)
    if not clean_name[0].isalpha():
        clean_name = f"Rule_{clean_name}"

    date_str = time.strftime("%Y-%m-%d")
    author = "LENSINT Automated Forensics & Threat Hunting Engine"
    description = f"Automated detection rule for {result.integrity.file_name or 'suspicious image payload'}"

    strings_lines = []
    conditions = []

    # 2. Magic byte container header
    has_magic = False
    is_tiff = False
    if result.integrity.detected_format == "JPEG":
        strings_lines.append('        $magic = { FF D8 FF }')
        has_magic = True
    elif result.integrity.detected_format == "PNG":
        strings_lines.append('        $magic = { 89 50 4E 47 0D 0A 1A 0A }')
        has_magic = True
    elif result.integrity.detected_format == "GIF":
        strings_lines.append('        $magic = { 47 49 46 38 }')
        has_magic = True
    elif result.integrity.detected_format == "WEBP":
        strings_lines.append('        $magic = { 52 49 46 46 }')
        has_magic = True
    elif result.integrity.detected_format == "BMP":
        strings_lines.append('        $magic = { 42 4D }')
        has_magic = True
    elif result.integrity.detected_format == "TIFF":
        strings_lines.append('        $magic = { 49 49 2A 00 }')
        strings_lines.append('        $magic_be = { 4D 4D 00 2A }')
        has_magic = True
        is_tiff = True

    # 3. YARA matched patterns or threat signatures
    str_idx = 1
    for hit in result.malware.yara_matches:
        if isinstance(hit, dict):
            for s in hit.get("strings_matched", []):
                if len(s) >= 4:
                    safe_s = s.replace("\\", "\\\\").replace('"', '\\"')
                    strings_lines.append(f'        $sig_{str_idx} = "{safe_s}" ascii wide nocase')
                    str_idx += 1
        elif isinstance(hit, str):
            safe_s = hit.replace("\\", "\\\\").replace('"', '\\"')
            strings_lines.append(f'        $sig_{str_idx} = "{safe_s}" ascii wide nocase')
            str_idx += 1

    # 4. Deobfuscated payloads
    for d in result.malware.deobfuscated_payloads:
        target = d.get("matched_target", "")
        if target:
            safe_t = target.replace("\\", "\\\\").replace('"', '\\"')
            strings_lines.append(f'        $deobf_{str_idx} = "{safe_t}" ascii wide')
            str_idx += 1

    # 5. Dangerous shell commands from strings scan
    for cmd in result.strings.iocs_detected.get("shell_commands", [])[:3]:
        safe_cmd = cmd.replace("\\", "\\\\").replace('"', '\\"')
        strings_lines.append(f'        $cmd_{str_idx} = "{safe_cmd}" ascii wide nocase')
        str_idx += 1

    # 6. Conditions
    if is_tiff:
        conditions.append("($magic at 0 or $magic_be at 0)")
    elif has_magic:
        conditions.append("$magic at 0")

    active_groups = []
    if any("$sig_" in s for s in strings_lines):
        active_groups.append("$sig_*")
    if any("$deobf_" in s for s in strings_lines):
        active_groups.append("$deobf_*")
    if any("$cmd_" in s for s in strings_lines):
        active_groups.append("$cmd_*")

    if active_groups:
        conditions.append(f"1 of ({', '.join(active_groups)})")
    else:
        conditions.append("filesize < 100MB")

    rule_template = f"""/*
   Auto-generated by LENSINT v2.5
   Target: {result.integrity.file_name}
   Severity: {result.overall_risk_level} (Risk Score: {result.overall_risk_score}/100)
*/

rule {clean_name}
{{
    meta:
        description = "{description}"
        author = "{author}"
        reference = "https://github.com/yxdooo/lensint"
        date = "{date_str}"
        sha256 = "{result.integrity.sha256}"
        severity = "{result.overall_risk_level}"
        risk_score = "{result.overall_risk_score}"

    strings:
{chr(10).join(strings_lines)}

    condition:
        {" and ".join(conditions)}
}}
"""
    return rule_template.strip()
    

def export_yara_rule(result: AnalysisResult, output_path: str, rule_name: Optional[str] = None) -> str:
    """Export deployable YARA rule to specified path, ensuring parent directories exist."""
    import os
    abs_path = os.path.abspath(output_path)
    parent_dir = os.path.dirname(abs_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    rule_str = generate_yara_rule(result, rule_name)
    with open(abs_path, "w", encoding="utf-8") as f:
        f.write(rule_str)
    return abs_path
